"use client";

import { Header } from "@/components/header";
import { ScrollToTop } from "@/components/scroll-to-top";
import { motion } from "framer-motion";
import { FileText } from "lucide-react";

const sections = [
  {
    id: "overview",
    title: "1. Overview of the HomeBids Platform",
    content: (
      <>
        <p>HomeBids operates a technology platform that connects homeowners seeking home services with independent contractors willing to provide those services.</p>
        <p>When a homeowner submits a project request through the Platform, the homeowner authorizes HomeBids to seek bids from contractors on their behalf.</p>
        <p>HomeBids may use automated systems, artificial intelligence, or manual outreach to:</p>
        <ul>
          <li>identify contractors relevant to the project</li>
          <li>share project details with contractors</li>
          <li>invite contractors to submit bids</li>
          <li>facilitate communication between homeowners and contractors</li>
        </ul>
        <p>HomeBids does not perform construction or home improvement services. HomeBids' role is limited to facilitating introductions between homeowners and contractors.</p>
      </>
    ),
  },
  {
    id: "authorization",
    title: "2. Authorization to Seek Bids",
    content: (
      <>
        <p>By submitting a project request, the homeowner expressly authorizes HomeBids to:</p>
        <ul>
          <li>identify contractors who may be interested in the project</li>
          <li>share project details with those contractors</li>
          <li>invite contractors to submit bids</li>
          <li>allow contractors to contact the homeowner directly</li>
        </ul>
        <p>HomeBids does not guarantee that any contractor will respond or submit a bid. Contractor availability and responsiveness may vary.</p>
      </>
    ),
  },
  {
    id: "independent-contractors",
    title: "3. Independent Contractors",
    content: (
      <>
        <p>All contractors using the Platform operate as independent businesses. HomeBids:</p>
        <ul>
          <li>does not employ contractors</li>
          <li>does not supervise contractor work</li>
          <li>does not control contractor pricing</li>
          <li>does not manage contractor projects</li>
        </ul>
        <p>HomeBids is not a contractor, subcontractor, broker, or agent of any contractor or homeowner. Contractors are solely responsible for licensing, insurance, permits, and compliance with applicable laws.</p>
      </>
    ),
  },
  {
    id: "no-construction",
    title: "4. No Construction Services Provided",
    content: (
      <>
        <p>HomeBids does not provide construction, repair, installation, or home improvement services.</p>
        <p>Any agreement for services is strictly between the homeowner and the contractor. HomeBids is not a party to any agreement or contract between users.</p>
      </>
    ),
  },
  {
    id: "no-project-management",
    title: "5. No Project Management or Payment Handling",
    content: (
      <>
        <p>HomeBids does not manage projects and does not process payments between homeowners and contractors. The Platform does not provide:</p>
        <ul>
          <li>escrow services</li>
          <li>project supervision</li>
          <li>dispute mediation</li>
          <li>contractor warranties</li>
          <li>project guarantees</li>
        </ul>
        <p>All project terms must be negotiated directly between homeowners and contractors.</p>
      </>
    ),
  },
  {
    id: "ai-discovery",
    title: "6. AI-Generated Contractor Discovery",
    content: (
      <>
        <p>HomeBids may use automated systems, artificial intelligence, and machine learning to identify contractors relevant to a homeowner's project. These systems may analyze:</p>
        <ul>
          <li>publicly available contractor data</li>
          <li>service categories</li>
          <li>geographic proximity</li>
          <li>business listings</li>
          <li>online reviews and ratings</li>
        </ul>
        <p>Contractor matches generated by these systems are informational only. HomeBids does not guarantee the accuracy or suitability of AI-generated contractor recommendations. Users agree to conduct their own due diligence before selecting a contractor.</p>
      </>
    ),
  },
  {
    id: "lead-generation",
    title: "7. Lead Generation Disclosure",
    content: (
      <>
        <p>HomeBids operates as a lead-generation platform. By submitting a project request, homeowners authorize HomeBids to distribute project details to contractors who may wish to bid on the work. Contractors may receive project opportunities through:</p>
        <ul>
          <li>automated notifications</li>
          <li>algorithmic matching</li>
          <li>direct invitations</li>
          <li>open bidding opportunities</li>
        </ul>
        <p>HomeBids does not guarantee that contractors receiving leads will submit bids. The Platform only facilitates introductions between parties.</p>
      </>
    ),
  },
  {
    id: "public-data",
    title: "8. Publicly Sourced Contractor Data",
    content: (
      <>
        <p>HomeBids may collect and organize contractor information that is publicly available online including:</p>
        <ul>
          <li>business listings</li>
          <li>publicly listed contact information</li>
          <li>business websites</li>
          <li>online reviews and ratings</li>
          <li>publicly available licensing information</li>
        </ul>
        <p>This information may be used to identify contractors relevant to projects and invite them to participate on the Platform. HomeBids does not guarantee the accuracy or completeness of publicly sourced data. Contractors may request updates or removal of their information.</p>
      </>
    ),
  },
  {
    id: "no-liability",
    title: "9. No Liability for Contractor Actions",
    content: (
      <>
        <p>To the maximum extent permitted by law, HomeBids is not responsible for:</p>
        <ul>
          <li>contractor performance</li>
          <li>contractor negligence</li>
          <li>contractor fraud or misconduct</li>
          <li>property damage</li>
          <li>personal injury</li>
          <li>construction defects</li>
          <li>project delays</li>
          <li>disputes between homeowners and contractors</li>
        </ul>
        <p>Homeowners must independently evaluate contractors before hiring them.</p>
      </>
    ),
  },
  {
    id: "user-responsibilities",
    title: "10. User Responsibilities",
    content: (
      <>
        <p>Users agree to:</p>
        <ul>
          <li>provide accurate information</li>
          <li>communicate respectfully</li>
          <li>comply with applicable laws</li>
          <li>conduct independent contractor evaluation</li>
        </ul>
        <p>Homeowners should verify contractor licensing, insurance, references, and qualifications.</p>
      </>
    ),
  },
  {
    id: "contractor-responsibilities",
    title: "11. Contractor Responsibilities",
    content: (
      <>
        <p>Contractors agree they:</p>
        <ul>
          <li>operate independent businesses</li>
          <li>maintain proper licensing and insurance</li>
          <li>comply with applicable laws</li>
          <li>provide accurate profile information</li>
        </ul>
        <p>HomeBids does not guarantee visibility or project opportunities.</p>
      </>
    ),
  },
  {
    id: "fees",
    title: "12. Platform Fees",
    content: (
      <>
        <p>Certain features of the Platform may require payment. Fees may include:</p>
        <ul>
          <li>subscription fees</li>
          <li>bid placement fees</li>
        </ul>
        <p>All fees are charged in advance and are generally non-refundable unless required by law. HomeBids may modify pricing at any time.</p>
      </>
    ),
  },
  {
    id: "communications",
    title: "13. Communications",
    content: (
      <>
        <p>Users consent to receive communications from HomeBids including:</p>
        <ul>
          <li>service notifications</li>
          <li>project alerts</li>
          <li>invitations to bid</li>
          <li>platform updates</li>
          <li>marketing communications</li>
        </ul>
        <p>These communications may be sent using automated systems. Users may opt out of non-essential communications.</p>
      </>
    ),
  },
  {
    id: "reviews",
    title: "14. Reviews and User Content",
    content: (
      <>
        <p>Users may submit reviews, ratings, and feedback. By submitting content, users grant HomeBids a worldwide license to display and publish that content. HomeBids may remove content that is abusive, fraudulent, misleading, or defamatory.</p>
      </>
    ),
  },
  {
    id: "suspension",
    title: "15. Account Suspension",
    content: (
      <>
        <p>HomeBids may suspend or terminate accounts that:</p>
        <ul>
          <li>violate these Terms</li>
          <li>engage in fraud or abuse</li>
          <li>harass other users</li>
          <li>provide misleading information</li>
        </ul>
        <p>Termination may occur without prior notice.</p>
      </>
    ),
  },
  {
    id: "disclaimer",
    title: "16. Disclaimer of Warranties",
    content: (
      <>
        <p>The Platform is provided &quot;as is&quot; and &quot;as available.&quot; HomeBids makes no warranties regarding contractor availability, qualifications, or project outcomes. All warranties are disclaimed to the fullest extent permitted by law.</p>
      </>
    ),
  },
  {
    id: "limitation",
    title: "17. Limitation of Liability",
    content: (
      <>
        <p>HomeBids&apos; total liability for any claim related to the Platform shall not exceed $100 or the amount paid to HomeBids in the previous 12 months, whichever is greater. HomeBids is not liable for indirect or consequential damages.</p>
      </>
    ),
  },
  {
    id: "indemnification",
    title: "18. Indemnification",
    content: (
      <>
        <p>Users agree to indemnify and hold harmless HomeBids and its affiliates from any claims arising from:</p>
        <ul>
          <li>contractor services</li>
          <li>property damage</li>
          <li>user conduct</li>
          <li>violation of these Terms</li>
          <li>disputes between users</li>
        </ul>
      </>
    ),
  },
  {
    id: "arbitration",
    title: "19. Arbitration Agreement",
    content: (
      <>
        <p>Any dispute related to the Platform shall be resolved through binding arbitration rather than court litigation. Users waive the right to participate in class-action lawsuits. Arbitration will follow the rules of the American Arbitration Association.</p>
      </>
    ),
  },
  {
    id: "governing-law",
    title: "20. Governing Law",
    content: <p>These Terms are governed by the laws of the State of Arizona.</p>,
  },
  {
    id: "changes",
    title: "21. Changes to Terms",
    content: (
      <>
        <p>HomeBids may update these Terms at any time. Continued use of the Platform after changes constitutes acceptance of the revised Terms.</p>
      </>
    ),
  },
  {
    id: "contact",
    title: "22. Contact",
    content: (
      <>
        <p>HomeBids</p>
        <p>[Insert Company Address]</p>
        <p>
          <a href="mailto:support@homebids.io" className="text-primary hover:underline">
            support@homebids.io
          </a>
        </p>
        <p>homebids.io</p>
      </>
    ),
  },
];

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          {/* Page header */}
          <div className="mb-12 text-center">
            <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10">
              <FileText className="h-7 w-7 text-primary" />
            </div>
            <h1 className="text-3xl font-bold text-foreground sm:text-4xl">Terms of Service</h1>
            <p className="mt-2 text-sm text-muted-foreground">These Terms govern your use of the HomeBids platform.</p>
            <p className="mt-1 text-xs text-muted-foreground/60">Last Updated: March 6, 2026</p>
          </div>

          {/* Intro */}
          <div className="mb-10 space-y-4 rounded-2xl border border-border bg-card p-6">
            <p className="text-muted-foreground">
              Welcome to <strong className="text-foreground">HomeBids</strong>. These Terms of Service (&quot;Terms&quot;) govern your access to and use of the HomeBids website, mobile application, and related services (collectively, the &quot;Platform&quot;).
            </p>
            <p className="text-muted-foreground">
              By creating an account, submitting a project request, bidding on a project, or otherwise using the Platform, you agree to these Terms.
            </p>
            <p className="text-muted-foreground">
              If you do not agree to these Terms, you may not use HomeBids.
            </p>
          </div>

          {/* Anchor nav */}
          <nav className="mb-12 rounded-2xl border border-border bg-card p-6" aria-label="Table of contents">
            <p className="mb-4 text-sm font-semibold text-foreground">Table of Contents</p>
            <ol className="grid gap-1.5 sm:grid-cols-2">
              {sections.map((s) => (
                <li key={s.id}>
                  <a
                    href={`#${s.id}`}
                    className="text-sm text-muted-foreground transition-colors hover:text-primary"
                  >
                    {s.title}
                  </a>
                </li>
              ))}
            </ol>
          </nav>

          {/* Sections */}
          <div className="space-y-10">
            {sections.map((s) => (
              <section key={s.id} id={s.id} className="scroll-mt-24">
                <h2 className="mb-4 text-lg font-semibold text-foreground">{s.title}</h2>
                <div className="space-y-3 text-muted-foreground [&_ul]:mt-2 [&_ul]:space-y-1.5 [&_ul]:pl-5 [&_ul]:list-disc [&_p]:leading-relaxed">
                  {s.content}
                </div>
                <div className="mt-10 border-b border-border" />
              </section>
            ))}
          </div>
        </motion.div>
      </main>

      <ScrollToTop />
    </div>
  );
}
